# --- Dynamic Plugin Manager ---
# 1. Define your plugins here (Format: "username/repository")
# You can add as many as you want to this list!
user_plugins=(
    "zsh-users/zsh-autosuggestions"
    "zsh-users/zsh-syntax-highlighting"
    "zsh-users/zsh-completions"
    "zsh-users/zsh-history-substring-search"
)

# 2. Set the custom plugin directory
CUSTOM_PLUGIN_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"

# 3. Loop through the list and install missing ones
for repo in $user_plugins; do
    # Extract the plugin name (everything after the last /)
    plugin_name="${repo##*/}"
    
    if [ ! -d "$CUSTOM_PLUGIN_DIR/$plugin_name" ]; then
        echo "Installing $plugin_name..."
        git clone --depth 1 "https://github.com/$repo" "$CUSTOM_PLUGIN_DIR/$plugin_name"
    fi
done
# --- End of Dynamic Manager ---



# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="jonathan"

plugins=(
    git
    archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

    
# Nvidia-specific environment variables for Hyprland
export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export CURSOR_FLAGS=--hw-cursor # Often needed for Nvidia

  

## Dotter Dotter completions 
source ~/dotfiles/completions/_dotter



# Check archlinux plugin commands here
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/archlinux

# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos
#pokemon-colorscripts --no-title -s -r #without fastfetch
pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# fastfetch. Will be disabled if above colorscript was chosen to install
#fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc

# Set-up icons for files/directories in terminal using lsd
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

# Set-up FZF key bindings (CTRL R for fuzzy history finder)
source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
